config/routes.rb
Rails.application.routes.draw do
  root to: 'todos#index'
  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy]
  
  def index
    @todos = Todo.all
  end

  def show
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)

    if @todo.save!
      redirect_to todos_path
    end
  end

  def edit
  end

  def update
    if @todo.update(todo_params)
      redirect_to todos_path
    end
  end

  def destroy
    @todo.destroy
    redirect_to todos_url, notice: "Todoが削除されました"
  end

  private

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:title,:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Crud
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    = yield

app/views/todos/create.html.slim
h1
  | Todos#create
p
  | Find me in app/views/todos/create.html.erb

app/views/todos/destroy.html.slim
h1
  | Todos#destroy
p
  | Find me in app/views/todos/destroy.html.erb

app/views/todos/edit.html.slim
= form_with model: @todo, local: true do |f|
  .form-group
    =f.label :title
    =f.text_field :title, class: 'form-control', id: 'task_title'
  .form-group
    =f.label :body
    =f.text_area :body, rows: 5, class: 'form-control', id: 'task_description'
  =f.submit nil, class: 'btn btn-primary'

  .nav.justify-content-end
  = link_to '一覧', todos_path, class: 'nav-link'

app/views/todos/index.html.slim
- @todos.each do |todo|
  tr
    th タイトル
    td = todo.title
    = link_to "詳細",todo_path(todo)
    = link_to "編集",edit_todo_path(todo)
    = link_to "削除",todo, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, status: :see_other, class: 'btn btn-danger'
  <br>
  tr
    th 内容
    td = todo.body
  <br>
  <br>
= link_to "新規作成", new_todo_path

app/views/todos/new.html.slim
h1 タスクの新規登録

.nav.justify-content-end
  = link_to '一覧', todos_path, class: 'nav-link'

= form_with model: @todo, local: true do |f|
  .form-group
    =f.label :title
    =f.text_field :title, class: 'form-control', id: 'task_title'
  .form-group
    =f.label :body
    =f.text_area :body, rows: 5, class: 'form-control', id: 'task_description'
  =f.submit nil, class: 'btn btn-primary'

  div
    h1 ピカわかメニュー
    ul
      li Ruby
      li Rails
      li HTML 

  div
    h1 pikawakaメニュー
    ul
      li ruby
      li rails
      li html

div
html
meta
header
footer
table
h1
p
a
ul
li

p
  | pikawaka

p
  |
    ピカイチわかりた垂<br>
    プログラ mキングサイトです

p
  |
    ピカイチわかりやすい<br>
    プログラミングサイトです

    a href='http://www.pikawaka.com' ピカわか

#pikawaka 
  ピカ

div.pikawaka
  ピカ
  
.pikawaka
  ピカ

#pikawaka.hoge.huga 
  ピカ

.pikawaka.hoge

/ :javascript


/ 
/ - @users.each do |user|
/ = user.title

app/views/todos/show.html.slim
h1 Todo詳細

= @todo.id
= @todo.title
= @todo.body
= link_to "編集",edit_todo_path(@todo.id)
= link_to "削除",@todo, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, status: :see_other, class: 'btn btn-danger'


= link_to '一覧', todos_path, class: 'nav-link'

app/views/todos/update.html.slim
h1
  | Todos#update
p
  | Find me in app/views/todos/update.html.erb